#!/bin/bash
# Counter Strike 1.6 serverio atnaujinimo skriptas
# Autorius: aaarnas
# amxmodx.lt

BASEDIR=$(dirname $(readlink -f $0))
MAIN_DIR="/usr"

STEAMCMD_URL="http://media.steampowered.com/client/steamcmd_linux.tar.gz"
STEAMCMD_DIR="$MAIN_DIR/steamcmd"
STEAMCMD_CMD="steamcmd.sh"
STEAMCMD_COMMANDS_FILE="/usr/_steamcmd_commands_list.txt"

if [ ! -e "$BASEDIR/cstrike" ]; then
	echo "-------------------------------------------------------------------------------"
	echo "Skriptas yra ne serverio direktorijoje. Iseinama..."
	exit
fi

SERVER_NAME=$(cat cstrike/server.cfg | egrep "hostname\s+\"[^\"]+\"" | sed "s/hostname //" | tr -d "\"\r")
EXITVAL=$?
if [ $EXITVAL -gt 0 ]; then
	echo "-------------------------------------------------------------------------------"
	echo "SteamCMD vidine klaida. Klaidos kodas: $EXITVAL"
	echo "Instaliacija nutraukiama..."
	exit 1
fi

if [ ! -e "$STEAMCMD_DIR/$STEAMCMD_CMD" ]; then
	if [ ! -e $STEAMCMD_DIR ]; then
		mkdir $STEAMCMD_DIR
	fi
	cd $STEAMCMD_DIR
	wget $STEAMCMD_URL
	tar -xzf steamcmd_linux.tar.gz
	rm steamcmd_linux.tar.gz
fi

echo -e  "login anonymous\nforce_install_dir $INSTALL_DIR\napp_update 90 -beta beta validate\napp_update 90 -beta beta validate\napp_update 90 -beta beta validate\nquit" > $STEAMCMD_COMMANDS_FILE
$STEAMCMD_DIR/$STEAMCMD_CMD +runscript $STEAMCMD_COMMANDS_FILE
rm $STEAMCMD_COMMANDS_FILE

echo "-------------------------------------------------------------------------------"
echo "Serveris $SERVER_NAME atnaujintas"
echo "-------------------------------------------------------------------------------"

exit
# Counter Strike 1.6 serverio atnaujinimo skriptas
# Autorius: aaarnas
# amxmodx.lt